service: hows-my-driving-dc

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  environment:
    BUCKET: ${self:custom.bucket}

  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: arn:aws:ssm:us-east-1:704903784842:parameter/howsmydriving/*
    - Effect: Allow
      Action: kms:Decrypt
      Resource: arn:aws:kms:us-east-1:704903784842:key/11b9fec1-3ab3-42d4-87f7-25b78c45ea10
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  test:
    handler: handlers.test
    environment:
      DEBUG: 0
  register:
    handler: handlers.register
  subscribe:
    handler: handlers.subscribe
  crc:
    handler: handlers.crc
    events:
      - http:
          path: webhook.json
          method: get
  webhook:
    handler: handlers.webhook
    events:
      - http:
          path: webhook.json
          method: post
  archive:
    handler: src/handlers.archive

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package
  bucket: hows-my-driving-dc-html
resources:
  Resources:
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
